language: node_js
node_js:
  - "6.9"
cache:
  directories:
    - node_modules
notifications:
  email:
    on_failure: change
    on_success: change
dist: trusty
sudo: required
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm install -g firebase-tools
  - npm install -g @angular/cli
before_script:
  - npm prune
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - chmod +x ./ci/setup.sh
script:
  - ./ci/setup.sh
  - ng lint
  - ng test --single-run --code-coverage
  - ng e2e
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - npm run report-coverage
branches:
  only:
    - master
